//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strategies.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PalindromesStrategy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аннотация: Я – Баба-яга. Вообще-то меня зовут Алена, а Баба-яга – это титул, доставшийся мне по наследству вместе с тайными магическими знаниями. Мой возлюбленный, сам Кащей Бессмертный, души во мне не чает, и у нас скоро свадьба. Вот только мне в очередной раз «везет» – какой-то умник решил устроить на меня охоту. Ко всему прочему у нашего советника Виктора неожиданно проснулась любвеобильность, кот занят устройством личной жизни, меня охватила навязчивая идея вернуться домой в свою избушку, Кащей разгреба [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BabaJaga {
            get {
                return ResourceManager.GetString("BabaJaga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaaaaaaaaaaaaaaaaaaaaaaaaaaa
        ///[-.?!)(,:]–
        ///[-.?!)(,:]–
        ///[-.?)(,:]–
        ///The Project Gutenberg EBook of The Adventures of Sherlock Holmes
        ///by Sir Arthur Conan Doyle
        ///(#15 in our series by Sir Arthur Conan Doyle)
        ///
        ///Copyright laws are changing all over the world. Be sure to check the
        ///copyright laws for your country before downloading or redistributing
        ///this or any other Project Gutenberg eBook.
        ///
        ///This header should be the first thing seen when viewing this Project
        ///Gutenberg file.  Please do not remove it.  Do  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LargeTXT {
            get {
                return ResourceManager.GetString("LargeTXT", resourceCulture);
            }
        }
    }
}
